[package]
name = "revda"
version = "6.0.0"
authors = ["THMonster <5125031+THMonster@users.noreply.github.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.9", features = [] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
dioxus-icons = "0.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
reqwest = { version = "0.13", features = [ "json" ] }
serde_json = "1"
serde = { version = "1", features = [ "derive" ] }
anyhow = "1"
toml = "1"
directories = "6"
rand = "0.10"
tracing = "0.1"
chrono = "0.4"
# dmlive = { path = "../dmlive" }
dmlive = { git = "https://github.com/THMonster/dmlive", branch = "dev" }

[features]
default = ["desktop"]
# The feature that are only required for the web = ["dioxus/web"] build target should be optional and only enabled in the web = ["dioxus/web"] feature
web = ["dioxus/web"]
# The feature that are only required for the desktop = ["dioxus/desktop"] build target should be optional and only enabled in the desktop = ["dioxus/desktop"] feature
desktop = ["dioxus/desktop"]
# The feature that are only required for the mobile = ["dioxus/mobile"] build target should be optional and only enabled in the mobile = ["dioxus/mobile"] feature
mobile = ["dioxus/mobile"]
