function color_table()
{
    return [{"name": "default", "c": "#ffffff"},
            {"name": "default", "c": "#000000"},
            {"name": "default", "c": "#FFCCCC"},
            {"name": "default", "c": "#FF9999"},
            {"name": "default", "c": "#FF6666"},
            {"name": "default", "c": "#CC3333"},
            {"name": "default", "c": "#FF0033"},
            {"name": "default", "c": "#FFCC99"},
            {"name": "default", "c": "#FF9966"},
            {"name": "default", "c": "#FF9900"},
            {"name": "default", "c": "#FF6600"},
            {"name": "default", "c": "#FFFF00"},
            {"name": "default", "c": "#CCCC33"},
            {"name": "default", "c": "#CCFF99"},
            {"name": "default", "c": "#009966"},
            {"name": "default", "c": "#339933"},
            {"name": "default", "c": "#CCCC66"},
            {"name": "default", "c": "#66CCCC"},
            {"name": "default", "c": "#66CC99"},
            {"name": "default", "c": "#339999"},
            {"name": "default", "c": "#CCFFFF"},
            {"name": "default", "c": "#3399CC"},
            {"name": "default", "c": "#99CCFF"},
            {"name": "default", "c": "#6699CC"},
            {"name": "default", "c": "#9999FF"},
            {"name": "default", "c": "#6666FF"},
            {"name": "default", "c": "#6666FF"},
            {"name": "default", "c": "#CCCCFF"},
            {"name": "default", "c": "#9966CC"},
            {"name": "default", "c": "#CC99CC"},
            {"name": "default", "c": "#FF99CC"},
            {"name": "default", "c": "#FF3399"}];
}
