/* generated by rust_qt_binding_generator */
#ifndef BINDING_H
#define BINDING_H

#include <QtCore/QObject>
#include <QtCore/QAbstractItemModel>

class QLivePlayerLib;

class QLivePlayerLib : public QObject
{
    Q_OBJECT
public:
    class Private;
private:
    Private * m_d;
    bool m_ownsPrivate;
    explicit QLivePlayerLib(bool owned, QObject *parent);
public:
    explicit QLivePlayerLib(QObject *parent = nullptr);
    ~QLivePlayerLib();
    Q_INVOKABLE QString get_danmaku();
    Q_INVOKABLE QString get_url(const QString& room_url, const QString& extras) const;
    Q_INVOKABLE void run_danmaku_client(const QString& room_url);
    Q_INVOKABLE void stop_danmaku_client();
Q_SIGNALS:
};
#endif // BINDING_H
